ykjit/ykllvm

llvm/lib/Transforms/Yk/BlockDisambiguate.cpp
llvm/lib/Transforms/Yk/ControlPoint.cpp

See commits.
The main work is in d32ff9f42.
The other commit is unrelated, but I'm sneaking it in here.
A companion PR is ~~coming~~ here: https://github.com/ykjit/yk/pull/444. That PR will be merged last.
The PR you are currently looking at will need to be merged first.

Simple trace stitching

---

llvm/lib/Transforms/Yk/ControlPoint.cpp

Companion to https://github.com/ykjit/yk/pull/446
The PR you are looking at now must be merged first.

Remove newline from debug string.

---

llvm/lib/Transforms/Yk/ControlPoint.cpp

This change moves some of the (compile-time generated) control point
logic into Rust code. Functionally this change is a no-op.
The plan is to keep as little code in compile-time generated LLVM IR, as
it's quite laborious to write and experiment with. Also we are about to
grapple with concurrency, and doing that in compile-time generated IR
would be a nightmare.
A companion PR ~will be up soon~ is [here](https://github.com/ykjit/yk/pull/447). The PR you are viewing now will go in first.

Move most of the control point logic into to Rust code.

---

llvm/lib/Transforms/Yk/ControlPoint.cpp

Previously we'd pass the control point its live variables in a struct by value, and it would return a (potentially mutated) struct containing the new state.
Like this:
```
%new_vars = new_control_point(YkLocation *%loc, YkCtrlPontVars %vars)
```
This change makes it so that the struct is passed by pointer:
```
new_control_point(YkLocation *%loc, YkCtrlPontVars* %vars_ptr)
```
If the struct is mutated, it happens in-place. No new state is returned.
This is required so that we can pass opaque pointers to Rust forLaurie's proposed `transition_location()` rework.

Make control point work "by pointer".

---

llvm/include/llvm/Transforms/Yk/ControlPoint.h
llvm/lib/Transforms/Yk/ControlPoint.cpp

This is the companion to https://github.com/ykjit/yk/pull/454.
It's just for demonstration purposes at this point, so don't do a detailed review.

Companion to "hook in transition location properly".

---

.buildbot_dockerfile_debian

This makes ykllvm build with the new docker infrastructure.

Add Dockerfile for CI.

---

llvm/lib/Transforms/Yk/ControlPoint.cpp

Main change is in the first commit.
https://github.com/ykjit/yk/pull/475 includes a test for this.
The compiler-side should be merged first.

Check ctrlp inside loop

---

.buildbot.sh
llvm/lib/Transforms/Yk/ControlPoint.cpp
yk_format_new_files.sh

Fix formatting and improve surrounding support code.
See commits.

Fix formatting.

---

llvm/lib/Transforms/Yk/ControlPoint.cpp

See commits.
There is a companion PR coming soon. The PR you are looking at now will be merged first.

Mark function arguments live for the control point.

---

llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp

Even if fallthrough is possible.
A companion PR is ~coming soon~ [here](https://github.com/ykjit/yk/pull/533) which will explain what this is all about.

In SelectionDAG lowering, always emit a branch.

---

llvm/lib/Transforms/Yk/ControlPoint.cpp

Companion PR: https://github.com/ykjit/yk/pull/500
Since the stopgap interpreter may interpret through the exit from the
main interpreter loop, we can't just continue running from the control
point after it returns. The stopgap interpreter now tells us via its
return value whether we need to continue as normal, or exit the main
interpreter loop. This is currently done by returning a boolean from the
control point, where `true` means the stopgap interpreter has run out of
the main interpreter loop. In this case we simply need to return.
Note, that we actually also need to return the value of the return that
was interpreted by the stopgap interpreter. We currently don't do this
since it requires more changes to the control point (passing in a
pointer in which to store the return value).

Add conditional exit after control point.

---

llvm/include/llvm/Transforms/Yk/LivenessAnalysis.h
llvm/include/llvm/Transforms/Yk/Stackmaps.h
llvm/lib/CodeGen/TargetPassConfig.cpp
llvm/lib/Transforms/Yk/CMakeLists.txt
llvm/lib/Transforms/Yk/ControlPoint.cpp
llvm/lib/Transforms/Yk/LivenessAnalysis.cpp
llvm/lib/Transforms/Yk/StackMaps.cpp

This adds the stackmap insertion pass that Lukas need for his stack reconstruction work.
See commit messages for more info.
A companion PR will be needed for ykjit/yk -- coming soon.

Insertsmcalls

---

llvm/lib/CodeGen/CodeGen.cpp
llvm/lib/CodeGen/SelectionDAG/FastISel.cpp
llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp

This is working by chance! The correct way to add external storage for a CLI option is described here:
https://llvm.org/docs/CommandLine.html#internal-vs-external-storage

Fix the "-yk-no-fallthrough" flag.

---

llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
llvm/lib/Support/Yk.cpp
llvm/test/CodeGen/X86/basic-block-sections-labels.ll

This looks worse than it is. Most if it is just guarding (and thus indenting) a large chunk of existing code.
`yk` change soon.

Gate our changes to the `.llvmbbaddrmap` section.

---

llvm/include/llvm/CodeGen/AsmPrinter.h
llvm/include/llvm/Transforms/Yk/LivenessAnalysis.h
llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
llvm/lib/Support/Yk.cpp
llvm/lib/Target/X86/X86MCInstLower.cpp
llvm/lib/Transforms/Yk/ControlPoint.cpp
llvm/lib/Transforms/Yk/LivenessAnalysis.cpp
llvm/lib/Transforms/Yk/StackMaps.cpp

See commits for details. Companion PR: https://github.com/ykjit/yk/pull/589

Fix stackmaps.

---

llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp

In the last LLVM sync, I tickled a bug in the "large stackmap locations" support that we added to ykllvm a while back. It manifested when building yklua. An "I shouldn't have already visited this node" assertion fails:
```
ld.lld: llvm/lib/CodeGen/SelectionDAG/ScheduleDAGSDNodes.cpp:393: void llvm::ScheduleDAGSDNodes::BuildSchedUnits(): Assertion `N->getNodeId() == -1 && "Node already inserted!"' failed.
```
Upon inspecting the DAGs, the stackmap nodes contain glue and chain operands as constituents of live variables. That makes zero sense! We are effectively asking the compiler to record the location of something which isn't a piece of data!
It causes two incoming glue and chains edges for some stackmap nodes, hence the assertion failure (two visits instead of one).
This change omits …

Don't record chain or glue operands in stackmap DAG nodes.

---

.buildbot.sh
.buildbot_dockerfile_debian

I think this is the last PR like this :)

Use ninja for CI.

---

.buildbot.sh
lldb/tools/lldb-instr/CMakeLists.txt
llvm/lib/CodeGen/AsmPrinter/CMakeLists.txt
llvm/lib/Transforms/Yk/CMakeLists.txt

See commits.
Companion PR coming.

Fix building LLVM as shared objects

---

llvm/lib/Transforms/Yk/LivenessAnalysis.cpp
llvm/lib/Transforms/Yk/StackMaps.cpp

A couple of misc bits in ykllvm

---

.buildbot_dockerfile_debian

And use the newest packaged clang.

Update CI to Debian bookworm.

---

clang/lib/CodeGen/BackendUtil.cpp

**Required for https://github.com/ykjit/yk/pull/829 **
This adds `--newpm-passes <pipeline>`.
For consistency, this has the same semantics as LLVM's extant `--lto-newpm-passes` switch.
Note that by imitating `--lto-newpm-passes` we inherit a quirk: if you pass the empty string for the pipeline, you get the default pipeline, and not an empty pipeline as one might expect.
This is because the switches are backed by a string, and the existence of the switches is decided by checking for an empty string.
When the string is non-empty, it goes through a parsing function which annoying also has no way to specify an empty pipeline.
Ideally the switches would be backed by a `optional<string>` (or the parser would have a way to specify the empty pipeline), but: a) that would be a separate change, and …

Add the ability to customise the pre-link pipeline

---

llvm/include/llvm/CodeGen/AsmPrinter.h
llvm/include/llvm/MC/MCStreamer.h
llvm/include/llvm/YkIR/YkIRWriter.h
llvm/lib/CMakeLists.txt
llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
llvm/lib/CodeGen/AsmPrinter/CMakeLists.txt
llvm/lib/Support/Yk.cpp
llvm/lib/YkIR/CMakeLists.txt
llvm/lib/YkIR/YkIRWriter.cpp
yk_format_new_files.sh

Companion to https://github.com/ykjit/yk/pull/842

Start serialising our own Yk IR.

---

llvm/lib/YkIR/YkIRWriter.cpp

Companion to https://github.com/ykjit/yk/pull/847

Start fleshing out YkIR instructions.

---

llvm/lib/YkIR/YkIRWriter.cpp

Companion to https://github.com/ykjit/yk/pull/853

Improve unimplemented stuff and serialise instruction types.

---

llvm/lib/YkIR/YkIRWriter.cpp

Required for https://github.com/ykjit/yk/pull/858

Serialise the void type.

---

llvm/lib/YkIR/YkIRWriter.cpp

This fixes a limitation we discussed in a prior PR: https://github.com/ykjit/ykllvm/pull/82#discussion_r1338383984
It pretty much amounts to keeping track of what LLVM values became what Yk values, and passing down some indices.
No functional change.
(I checked that the IR of the `simple.newcg.c` didn't change with this commit).

Don't assume that there is a 1-1 mapping between LLVM an Yk IR instructions.

---

llvm/lib/YkIR/YkIRWriter.cpp

`llvm::AllocaInst` doesn't record the allocated type into its operand list, so a generic serialisation misses that info.

Serialise alloca properly.

---

llvm/lib/YkIR/YkIRWriter.cpp

Give branches some attention.

---

llvm/lib/YkIR/YkIRWriter.cpp

(yk PR ~~coming soon~~: https://github.com/ykjit/yk/pull/881)

Serialise function types and argument operands.

---

llvm/lib/YkIR/YkIRWriter.cpp

Kill debugging.

---

.buildbot.sh

Untested, but should be grand (famous last words).

Check ykllvm builds without assertions.

---

llvm/include/llvm/CodeGen/AsmPrinter.h
llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp

Companion PR to https://github.com/ykjit/yk/pull/891

Get ykllvm to provide enough info to identify a zero-length call.

---

llvm/lib/YkIR/YkIRWriter.cpp

Tidy up IR serialiser a bit

---

llvm/lib/YkIR/YkIRWriter.cpp

See https://github.com/ykjit/yk/pull/965 for related changes in yk.

More work on lowering LLVMIR to YKIR.

---

llvm/lib/CodeGen/Yk/FixStackmapsSpillReloads.cpp

Related: https://github.com/ykjit/yk/pull/939
Source: https://github.com/ykjit/yk/pull/939#issuecomment-1909980698
The yk_trace_basicblock call doesn't require stackmaps therefore we can skip stackmap adjustment for those functions.
Tests:
```
Testing Time: 405.04s
Skipped          :    46
Unsupported      :   885
Passed           : 92778
Expectedly Failed:   211
```

Skip stackmaps for yk_trace_basicblock.

---

llvm/lib/YkIR/YkIRWriter.cpp

This is for the soon-to-come yk change for processing binary operations in the trace builder.

Serialise binary operations.

---

llvm/lib/YkIR/YkIRWriter.cpp

Companion to https://github.com/ykjit/yk/pull/1019

Include the predicate in the ICmp lowering.

---

llvm/lib/Transforms/Yk/StackMaps.cpp

This reverts commit b13bfe1badfc8e805df9ef9b12f263c818e18c9c, reversing changes made to d68ef90374dce99e8a4fabafb1c95da47d286de6.

Revert Stackmap change from PR#119

---

llvm/lib/YkIR/YkIRWriter.cpp

See commits.
Companion to https://github.com/ykjit/yk/pull/1056

Custom lower condbr (and small fixes)

---

llvm/lib/YkIR/YkIRWriter.cpp

Fix varargs

---

llvm/lib/YkIR/YkIRWriter.cpp

Main work in https://github.com/ykjit/ykllvm/commit/cf4476ee2eebebd60e7349a6048349d676991dac.

Fold binops into one opcode.

---

llvm/lib/YkIR/YkIRWriter.cpp

companion to https://github.com/ykjit/yk/pull/1092

Remove unused duplicate BinaryOperator opcode.

---

llvm/lib/YkIR/YkIRWriter.cpp

Companion to https://github.com/ykjit/yk/pull/1106

Send the function index for local variable operands.

---

llvm/lib/YkIR/YkIRWriter.cpp

Required for the upcoming outlining PR in yk.

Serialise outlining function attribute.

---

llvm/lib/YkIR/YkIRWriter.cpp

We'll need this for the new outlining algorithm.

Serialise the successor block of unconditional branches.

---

llvm/lib/YkIR/YkIRWriter.cpp

Companion to https://github.com/ykjit/yk/pull/1117

Serialise sign extend instructions.

---

llvm/lib/YkIR/YkIRWriter.cpp

Companion to https://github.com/ykjit/yk/pull/1123

Serialise switch instructions.

---

llvm/lib/YkIR/YkIRWriter.cpp

Instead of serialising stack-maps as separate instructions with their own opcode, we fold them up into the instruction that they act as a safepoint for (i.e. `call` or `condbr` instrs).

Serialise stack-maps on demand

---

llvm/lib/YkIR/YkIRWriter.cpp

In the last PR I added the ability to "patch-up later" instruction indices that are as-yet unknown. I stashed the info needed for this in a new field in the YKIRWriter.
However, since that info is "per-function", there's no need to keep it alive that long. In fact the lifetime is the same as the `VLMap`.
This change groups the VLMap and the patch-up info together into a `FuncLowerCtxt`. A fresh one of these is created for each LLVM function we lower, and it is then passed down through the serialiser using no object state from `YkIRWriter`. When we are done lowering a function, we allow the `FuncLowerCtxt` to fall out of scope, thus better capturing the lifetime of this information and preventing accidental reuse.
No functional change.

Tidy up "patch-up" logic.

---

llvm/lib/YkIR/YkIRWriter.cpp

getelementptr is full of semantic details. This change makes our lowering much more defensive in an attempt to get things right (tm).
This was the result of a full day of reading/musing, starting with:
https://llvm.org/docs/LangRef.html#getelementptr-instruction
and:
https://llvm.org/docs/GetElementPtr.html
and:
https://llvm.org/docs/LangRef.html#poisonvalues
We still can't handle everything that could theoretically be possible, but a) for now those cases are unlikely to arise for us, and b) I've asserted them, so we can catch them early if they do arise.
I hope I've got it right!

Be more systematic in serialising GEP instructions.

---

llvm/lib/YkIR/YkIRWriter.cpp

Reject allocas we don't support and include alignment in the lowered instruction.

Alloca serialisation tweaks.

---

llvm/lib/YkIR/YkIRWriter.cpp

See individual commits.
(not many instructions to audit left after this)

Unsupported phi and casts

---

llvm/lib/YkIR/YkIRWriter.cpp

yk change coming soon.
Currently we only allow through loads and stores where the alignment of the operation is equal the natural alignment of the type of the data being loaded/stored.
However, we can also allow through cases where the alignment of the operation is *greater* than the natural alignment of the data being loaded/stored. In such a case a read/write from memory could never straddle the alignment boundary.
The LLVM lang ref says:
> An alignment value higher than the size of the loaded type implies
> memory up to the alignment value bytes can be safely loaded without
> trapping in the default address space

Allow loads and stores with align >= the size of the data.

---

llvm/lib/YkIR/YkIRWriter.cpp

Serialise volatile memory accesses.

---

llvm/lib/YkIR/YkIRWriter.cpp

Basic floating point lowerings.

---

llvm/lib/YkIR/YkIRWriter.cpp

Remove argument operands from the AOT IR by replacing them with instructions that we insert into the first block.
Taking the following LLVM IR as an example:
```
func main($1) {
bb0:
$2 = add $1, 0
}
```
Previously, this would become in our AOT IR:
```
func main(%1) {
bb0:
$1 = add arg(0), 0
}
```
Now this would become:
```
func main(%1) {
bb0:
$1 = arg(0)
$2 = add $1, 0
}
```
Essentially, this gets rid of all argument operands in our AOT IR which simplifies `trace_builder` and especially deopt, which now have one less operand kind to handle.

Replace argument operands with instructions.

---

llvm/lib/YkIR/YkIRWriter.cpp

For now only `float` and `double` support.

Add floating point constant lowering support.

---

llvm/lib/YkIR/YkIRWriter.cpp

The format is very dumb and could doubtfully be optimised later. I just wanted to get *something* working to iterate upon for now.

Serialise line-level debug information into the AOT IR.

---

llvm/lib/YkIR/YkIRWriter.cpp

Type unimplemented AOT instructions.

---

llvm/lib/CodeGen/Yk/FixStackmapsSpillReloads.cpp

When fixing spill reloads between a call and its stackmap instruction, we assumed that spill reloads are only of the form:
```
call foo()
mov restored_reg1, [rbp - spill_off]
mov restored_reg2, spill_reg
```
However, there can be cases where a spill reload looks like this:
```
call foo()
mov tmp, [rbp - spill_off]
mov restored_reg, tmp
```
In other words, the register allocator may use temporary registers when restoring spills.
This commit fixes our FixStackmapsSpillReloads pass to handle these cases by applying spills to temporary registers to the correct target register.

Fix unhandled case in FixStackmapsSpillReloads pass.

---

llvm/lib/Transforms/Yk/ShadowStack.cpp

One can see this a minor optimisation, but the more important change from our perspective is that it removes an alias where "y = gep x, 0" allows later stages of the pipeline to treat `x` and `y` as aliases, causing minor confusion for parts of yk. Note that the aliasing is always correct -- it's just a bit annoying for us to have to deal with.

In the shadowstack, don't turn an offset of 0 into a GEP.

---

llvm/lib/Transforms/Yk/ControlPoint.cpp

Tidy cp pass

---

llvm/lib/Transforms/Yk/LivenessAnalysis.cpp

I feel this better explains the problem and how it is solved.

Explain the PHI liveness quirk using ASCII art.

---

llvm/lib/YkIR/YkIRWriter.cpp

[explanation in yk companion PR]

Serialise the type of a PHI operation.

---

llvm/lib/YkIR/YkIRWriter.cpp

yk change with a test coming soon.

Lower non-truncating inttoptr to zext instructions.

---

llvm/lib/YkIR/YkIRWriter.cpp

Serialise bitcasts.

---

llvm/lib/Target/X86/X86AsmPrinter.cpp

Fix defs again

---

llvm/lib/YkIR/YkIRWriter.cpp

In preparation for adding the elidable attribute.

Convert the "outline" boolean field into a flags bitfield.

---

llvm/lib/YkIR/YkIRWriter.cpp

Before we piggy backed on zext, which was confusing.

Lower ptrtoint and inttoptr to decicated AOT bytecodes.

---

llvm/lib/Transforms/Yk/ShadowStack.cpp

Sometimes an alloca doesn't have a known size at compile-time (e.g. an array with a non-const size). When this happens, we can't pre-compute its stack frame size so we don't know how big to make the shadow stack.
For now, when we encounter such cases we outline the function, preventing it from being traced at all, this obviates the need for a shadow stack at all.

Correct handling of dynamically sized Allocas

---

llvm/lib/Transforms/Yk/ShadowStack.cpp
llvm/test/Transforms/Yk/ShadowStackDebug.ll

This reverts commit 6507d0668f39ba490a5ecb89ec693614a41557c8.

Reapply "Make shadow stack debuggable"

---

llvm/lib/Transforms/Yk/StackMaps.cpp

When inserting stackmaps we were previously assigning ids out of order, due to `std::map` sorting them by their pointer value. This meant that re-compiling a binary with minimal or no changes could result in stackmap ids being completely different than in the previous binary. This made our life unneccessarily difficult during debugging or when diffing traces.
Using a vector instead of a map fixes this and stackmap ids should be more concistent across re-compilations now (unless the source has been changed consideribly of course).

Make stackmap ids determinstic across compilations.

---

llvm/lib/YkIR/YkIRWriter.cpp

(and demonstrate on unimplemented call instructions)
example runtime output:
```
not yet implemented: Unimplemented { tyidx: TyIdx(2), llvm_inst_str: "  %33 = tail call noalias ptr @fopen64(ptr noundef %1, ptr noundef %2) <note: noalias>" }
```

Add the ability to attach a note to unimplemented instructions.

---

llvm/lib/Transforms/Yk/BasicBlockTracer.cpp

Before this change, our system runs nbody about 4.7x that of upstream Lua.
First I confirmed that it's nothing to do with the quality of the traces we are building (they are pretty much the same as we make with HWT, with some inevitable variation due to the need for trace recorder calls).
perf tells me that __trace_basicblock() is the single biggest cost of SWT (67% of nbody). I then double checked this by running nbody without the JIT enabled, comparing performance with and without the SWT recorder pass enabled (--yk-basicblock-tracer). With this flag enabled, we are 4.2x that of without!
So the main cost is undoubtedly recording blocks.
The first thing we can do is not insert calls to the block recorder in functions marked yk_outline. That's what this change does.
This gives us an 84% …

Don't insert basicblock tracer calls in yk_outline functions.

---

llvm/lib/Transforms/Yk/ModuleClone.cpp
llvm/test/Transforms/Yk/ModuleClone.ll

Address-taken functions are treated as unoptimised, with having actual tracing calls. These functions should have their internal function calls to reference other unoptimised functions.
Let `luaB_setmetatable` is a function with address taken.
`luaB_setmetatable` calls `luaL_getmetafield` while it should be calling `__yk_unopt_luaL_getmetafield`.
```llvm
func luaL_getmetafield(%arg0: ptr, %arg1: i32, %arg2: ptr) -> i32 {
...
func luaB_setmetatable(%arg0: ptr) -> i32 {
...
call __yk_trace_basicblock(630i32, 13i32)
%13_1: i32 = call luaL_getmetafield(%0_0, 1i32, @.str.37.695) [safepoint: 4346i64, (%0_0)]
br bb14
func __yk_unopt_luaL_getmetafield(%arg0: ptr, %arg1: i32, %arg2: ptr) -> i32 {
...
```

Fix address-taken functions call references in ModuleClone.

---

llvm/include/llvm/Support/Yk.h
llvm/include/llvm/Transforms/Yk/OutlineUntraceable.h
llvm/lib/CodeGen/TargetPassConfig.cpp
llvm/lib/Support/Yk.cpp
llvm/lib/Transforms/Yk/CMakeLists.txt
llvm/lib/Transforms/Yk/OutlineUntraceable.cpp

The meat is dbc81d68e7b57be4f4ba330cccb457d49ff6ee20.

Mark untraceable functions yk_outline

---

llvm/lib/YkIR/YkIRWriter.cpp

This shaves off around 4 minutes of link-time on a release build of ykruby.

Precompute indices for IR serialisation

---

llvm/lib/Transforms/Yk/ControlPoint.cpp

In multiple function and module passes we need to identify the control point functions. This required a O(n) pass over every instruction in the module. Since control point functions are immutable, we now cache these lazily after the first search. Multiple passes can benefit from this. E.g. This change improves OutlineUntraceable wall-clock time on ykruby from 2 minutes to 3 seconds on release builds.

Cache control point function lookups
