ykjit/ykllvm

- llvm/CMakeLists.txt
- llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
Since LLVM reorders machine basic blocks during compilation, the order
in the basic block address map doesn't match the order of LLVM IR basic
blocks.
This PR extends the basic block address map
(SHT_LLVM_BB_ADDR_MAP) with an additional field which exposes the LLVM
IR basic block index for each machine basic block. This allows us to map
virtual addresses back to BasicBlocks in the IR.
> Extend basic block address map with IR indexes.

- llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
In a previous PR we modified the `.llvm_bb_addr_map` section, adding the
orignial basic block index. This commit improves that code in two ways:
1) Catch the case where MachineBasicBlock::getBasicBlock() returns a
null pointer. To quote the documentation:
> Note that this may be NULL if this instance does not correspond
> directly to an LLVM basic block.
We use the block index u64::MAX to encode this condition (note that
although the field in the section is uleb128, LLVM only allows block
indices that fit in a u64).
An upcoming change to yk will check for this condition at runtime.
2) Currently if a block isn't found, then the resulting block index is
incorrect: The last index used in the loop is erroneously used.This
commit causes an error at compile time instead.
> Make finding the corresponding BasicBlock more robust.

- llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
[@ptersilie will raise a companion PR shortly]
During code-gen, LLVM may merge more than one BasicBlock into a single
MachineBasicBlock. In such cases MachineBasicBlock::getBasicBlock() will
return the first BasicBlock into which the other blocks were merged. For
Yk to correctly assemble a JIT trace, it needs to know all of the
corresponding BasicBlocks for any given MachineBasicBlock. To that end,
this change stores the indices of all corresponding BasicBlocks in the
block address map (not just the first block).
To find the corresponding BasicBlocks we:
- Compute the set of BasicBlocks that are not observed when calling
MachineBasicBlock::getBasicBLock() on all MBBs in the parent
MachineFunction, MF. These are the BasicBlocks that were merged with
other BasicBlocks during code-gen.
- If …
> Store all corresponding BasicBlocks in the block address map.

- llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
The `embed-bitcode` flag serialises the IR after only architecture
agnostic optimisations have been run, but then proceeds to apply other
optimisations afterwards. Sometimes, this final version is precisely
what we are interested in. The `embed-bitcode-final` flag waits until
all optimisations have been run before embedding the IR.
> Add flag to embed final bitcode.

- llvm/include/llvm/Transforms/Yk/BlockDisambiguate.h
- llvm/lib/CodeGen/CMakeLists.txt
- llvm/lib/CodeGen/TargetPassConfig.cpp
- llvm/lib/LTO/CMakeLists.txt
- llvm/lib/Passes/CMakeLists.txt
- llvm/lib/Transforms/Yk/BlockDisambiguate.cpp
- llvm/lib/Transforms/Yk/CMakeLists.txt
This is required for yk to unambiguously map machine blocks back to IRblocks.
See the doc comment in [`BlockDisambiguate.cpp`](https://github.com/ykjit/ykllvm/pull/11/files#diff-6fe45f14428841c1072fb97dfa17cc765f4de37342460c80ace7125111a40d9eR1) for a detailed description of the problem this solves and how we solve it.
[that comment took many hours to get right -- it's really "detaily" and hard to explain]
A companion PR will come soon. This PR should be merged first.
> Add the yk BlockDisambiguate pass.

- llvm/include/llvm/Transforms/Yk/ControlPoint.h
- llvm/lib/CodeGen/TargetPassConfig.cpp
- llvm/lib/LTO/LTOBackend.cpp
- llvm/lib/Transforms/Yk/BlockDisambiguate.cpp
- llvm/lib/Transforms/Yk/ControlPoint.cpp
687a98ffb5 is the main body of work, but a couple of other changes were required to get things working correctly. So see individual commits.
Companion PR ~coming soon~ [here](https://github.com/ykjit/yk/pull/445). The PR you are looking at now will be merged first.
> Make the control point accept a `ykrt::Location` instead of an integer.

- llvm/lib/Target/X86/X86FastISel.cpp
When using intrinsics, such as `memcpy`, in LLVM IR, the compiler may
decide to inline/optimise them during codegen, or leave them as is. This
makes mapping a PT trace back to LLVM IR difficult, since we don't know
whether to expect a hole in the trace (from the call to the intrinsic)
or not.
There's two ways to solve this: 1) Remove all optimisations that inline
intrinsic 2) annotate intrinsics with metadata so we can identify
inlined intrinsics during trace construction (in `JITModBuilder`).
The problem with the first approach is that these optimisations are not
in a single place and spread out through different optimisation levels
and even architectures. This makes them easy to miss, which we will only
notice when traces behave in unexpected ways (if we're lucky the trace
compiler …
> Annotate intrinsic calls with inlining decisions.

- llvm/lib/Target/X86/X86ISelLowering.cpp
This is a companion PR to https://github.com/ykjit/yk/pull/504
Works around https://github.com/ykjit/yk/issues/502
> Add a switch to disable tail call optimisations on x86_64.

- llvm/lib/Target/X86/X86FastISel.cpp
- llvm/lib/Transforms/Yk/BlockDisambiguate.cpp
This addresses an issue where the mapper collapses direct recursion (a function calling itself) bubbling up (confusing it for internal control flow at the machine basic block level).
This is involved.
I wouldn't recommend trying to understand what I've added without first reviewing the large module-level comment first. I expect this will be a task for Lukas, as it's unfair to ask Laurie to digest that stuff afresh.
> Return from direct recursion disambiguation

- clang/include/clang/Basic/Attr.td
- clang/include/clang/Basic/AttrDocs.td
- clang/lib/CodeGen/CodeGenModule.cpp
- clang/test/Misc/pragma-attribute-supported-attributes-list.test
This annotations does two things:
- It tells the Yk JIT to *not* inline calls to the function in into JIT
traces.
- It adds the `noinline` attribute, thus preventing LLVM from inlining
calls to the function when compiling JIT traces.
A `yk` companion PR ~will come soon~ is [here](https://github.com/ykjit/yk/pull/531).
Merge the companion PR last.
Raising as a draft, because I'm now questioning the name of the annotation.
"do not trace" feels weird in the context of the hardware tracer. PT will always trace everything, whether we like it or not, and then our annotation retroactively un-inlines (outlines) the inlined code. So is `yk-outline` a better annotation name for us?
> Add the `yk_outline` function attribute.

- llvm/lib/Transforms/Yk/ControlPoint.cpp
Before we considered any value whose definition dominates the call to
the control point as being a live variable. This is correct in the sense
that in includes all of the necessary live variables, but is obviously
an over-approximation (it includes things which have died in the lead-up
to the call to the control point).
Having lots of unnecessary variables in the live set makes the JIT IR
larger than necessary and imposes a higher memory footprint at the time
of calling the control point (where we pass a big struct of live
variables).
This change implements a precise liveness analysis in order to whittle
the live set down to the bare essentials.
We use the algorithm from Modern Compiler Implementation in Java (2nd
edition), by Andrew W. Appel.
Fixes https://github.com/ykjit/yk/issues/515
> Implement more precise liveness analysis.

- llvm/lib/Transforms/Yk/ControlPoint.cpp
Sometimes we were letting through invalid IR, which may or may not be
detected at runtime.
(Oddly `parseIR()` doesn't always detect invalid IR, even with
assertions on!)
Companion PR [here](https://github.com/ykjit/yk/pull/538).
> In debug builds, verify the IR after the control point pass.

- llvm/lib/Transforms/Yk/ControlPoint.cpp
Updates the control point pass to allocate some space in which the stopgap interpreter will store the value of the interpreter return, when it runs outside of the main interpreter loop during a guard failure.
Companion PR: https://github.com/ykjit/yk/pull/551
> Allow arbitrary return types in control points caller.

- .buildbot.sh
Since we disabled default PIE on the yk side (https://github.com/ykjit/yk/pull/559), we should probably do the same here for CI purposes.
> Turn off default PIE in CI.

- llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp
- llvm/test/CodeGen/X86/selectiondag-patchpoint-legalize.ll
- llvm/test/CodeGen/X86/selectiondag-stackmap-legalize.ll
To get an accurate view of a vector live variable, we have to
recursively search the DAG for the initial `BUILD_VECTOR` DAG node and
then look for `INSERT_VECTOR_ELT` nodes (element insertions) as we
bubble up from recursion, updating our view as we go.
Also Updated tests to cover this use case.
(The search technique was inspired by the `getUnderlyingArgRegs()`
function from the same file, which does something similar: recursively
searches for `CopyFromReg` nodes)
> Ensure that vectors are reported correctly in stackmaps.

- clang/include/clang/Basic/Attr.td
- clang/include/clang/Basic/AttrDocs.td
- clang/include/clang/Basic/CodeGenOptions.def
- clang/include/clang/Driver/Options.td
- clang/lib/CodeGen/CodeGenModule.cpp
- clang/lib/Driver/ToolChains/Clang.cpp
- clang/test/Misc/pragma-attribute-supported-attributes-list.test
- clang/test/Yk/yk_noinline_loopy_funcs.c
This function attribute tells the Yk JIT that it is OK to inline the decorated function into the trace, even if it contains loops.
It follows that from now on, any function containing a loop will not be inlined into traces by default.
This change also introduces an "internal" `__yk_hasloop` annotation, which is used by the JIT to know if a function contains loops.
**A companion PR will follow**
This change adds one *clang* attribute:
- `yk_unroll_safe`
And adds two *llvm* attributes:
- `yk_unroll_safe`
- `__yk_has_loop`
Just as I am raising this PR, I realise that I can simplify things: the clang `yk_unroll_safe` annotation could lower to the existing llvm `yk_outline` annotation and we can also only apply this annotation if the function has no loops, thus making `__yk_has_loop` redundant …
> Add the `yk_unroll_safe` attribute.

- llvm/lib/Bitcode/Writer/BitcodeWriter.cpp
- llvm/lib/CodeGen/TargetLoweringObjectFileImpl.cpp
- llvm/lib/Support/CMakeLists.txt
- llvm/lib/Support/Yk.cpp
Enabling this flag does three things:
- Adds the `SHF_ALLOC` flag to the `.llvmbc` section so that it gets loaded by the loader.
- Makes the `llvm.embedded.module` symbol inside externally visible by giving it external linkage.
- Prepends the embedded IR with a pointer-sized length field so that we can load the IR directly from memory at runtime.
I was having issues finding a place to define the flag where it could be consistently accessed across the necessary module linkage boundaries. I've ended up defining  it in `llvm/lib/Support`, which is an "always linked" component.
> Add the `-yk-alloc-llvmbc-section` flag.

- llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
- llvm/lib/MC/MCObjectFileInfo.cpp
- llvm/lib/Support/Yk.cpp
[Companion PR: ~for the runtime coming soon~ https://github.com/ykjit/yk/pull/571]
We make the section loadable and emit symbols to help us find the data at runtime.
LLVM streams the BB data for each function (independently) out to the binary on the fly. This makes it hard to provide the runtime with a simple `(address, length)` pair that it needs to make a Rust slice of the data.
We work around this like so: for each function we emit a start and end symbol marking the bbaddrmap data for the function. The name of the symbol encodes the function for which the BB data corresponds. The runtime knows what functions are available (from the LTO LLVM IR) and can therefore enumerate the symbols to find all of the BB data.
> Make it so we can read the `.llvm_bb_addr_map` section from memory at runtime

- llvm/include/llvm/CodeGen/StackMaps.h
- llvm/include/llvm/Transforms/Yk/ControlPoint.h
- llvm/lib/CodeGen/StackMaps.cpp
- llvm/lib/Transforms/Yk/ControlPoint.cpp
- llvm/test/CodeGen/X86/statepoint-stackmap-size.ll
This is a companion PR to https://github.com/ykjit/yk/pull/578 and adds function prologue information (e.g. callee-saved registers, pushed RBP) to stackmaps, which are required in order to do stack reconstruction during guard failures.
> Add function prologue info to stackmaps.

- llvm/include/llvm/CodeGen/AsmPrinter.h
- llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
Prior to this change, each *function* would get a start/stop symbol pair and the runtime would need to know the names of all the functions in order to load each map from the `.llvm_bb_addr_map` section.
The problem with that approach is that to know the names of all of the functions, you need to also have the LLVM IR in order to iterate over the functions in the module. To do that, you need to have the LLVM IR parser, which means linking LLVM.
In upcoming work (for the fast ykpt trace decoder), the block map parser will need to be moved out of `yk` and into `hwtracer`, so that hwtracer can pick up the decoding hints we are going to add to the block map.
It seems unreasonable and cumbersome for `hwtracer` to have to link LLVM just to load the blockmap.
This change uses *section* start and …
> Switch to section start/stop markers for the `.llvm_bb_addr_map` section.

- llvm/include/llvm/CodeGen/AsmPrinter.h
- llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
- llvm/test/CodeGen/X86/basic-block-sections-labels.ll
This change does a couple of things. For each basic block we add:
- A table of call offsets.
- Information about statically known successors.
In combination, this gives us enough information for a PT decoder
(specifically our ykpt decoder) to make sense of a PT packet stream
without the need to do static disassembly of the instruction steam
(which would be slow).
Note that to get the call offsets, we have to insert symbols into the
binary, and their presence would break a lot of upstream LLVM tests.
For now I've gated the insertion of the symbols in with
`YkAllocBBAddrMapSection`.
I've noticed that our .llvm_bb_addr_map extension have not been gated.
My next change should probably be an all-encompassing
`YkExtendedAddrMap` gate, which encompasses all of our addr map
changes.
Companion to …
> Extend the .llvm_bb_addr_map section with PT decoding hints.

- llvm/include/llvm/Transforms/Yk/ShadowStack.h
- llvm/lib/CodeGen/TargetPassConfig.cpp
- llvm/lib/Transforms/Yk/CMakeLists.txt
- llvm/lib/Transforms/Yk/ShadowStack.cpp
This PR adds a shadowstacks to fix the issue of sharing variables between AOT and JIT modules during deoptimisation. See commit messages for more details.
Since using the shadow stack means we now store (almost) all variables on the heap, there's a performance cost. I've ran a few Lua tests and here are the results (timings are in seconds):
| Test | Normal | Shadowstack | Slowdown |
| ----- | -----------| ------------------ | ------------- |
| sort | 0.07 | 0.17 | 2.4x |
| verybig | 0.27 | 0.32  | 1.18x |
| pm | 0.04 | 0.05 | 1.25x |
| constructs | 2.9 | 3.3 | 1.13x |
There's definitely room for improvement here, since there's no need to store ALL variables on the shadow stack. Variables which won't have their reference taken can continue to live on the normal stack, though we would need …
> Use shadowstack to share variables between AOT and JIT.

- llvm/include/llvm/CodeGen/TargetInstrInfo.h
- llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
- llvm/lib/Target/X86/X86InstrInfo.cpp
- llvm/lib/Target/X86/X86InstrInfo.h
This is required for dealing with compressed returns in the ykpt decoder.
Companion to https://github.com/ykjit/yk/pull/590
> blockmap: Split apart return edges from other dynamic edges.

- llvm/include/llvm/CodeGen/StackMaps.h
- llvm/lib/CodeGen/StackMaps.cpp
- llvm/lib/Support/Yk.cpp
- llvm/lib/Target/X86/X86AsmPrinter.cpp
- llvm/lib/Target/X86/X86AsmPrinter.h
- llvm/lib/Target/X86/X86MCInstLower.cpp
- llvm/lib/Transforms/Yk/StackMaps.cpp
Currently, stackmaps can only track one location per live variable, e.g. from the view of the stackmap a live variable is either in a register or on the stack. When deoptimising into machine code, this isn't sufficient since spilling will often create copies of a variable in multiple locations. This PR extends stackmaps to track an additional location for live variables in registers, i.e. in additional to the register location there can be another register location or a stack offset.
Note, that this makes some assumptions that may not hold in the general case, but will get us going on our way to fully trace Lua. We might have come back to revisit this code, if issues arise later on.
> Enable stackmap support for tracking multiple locations.

- llvm/lib/Target/X86/X86AsmPrinter.cpp
- llvm/lib/Transforms/Yk/ControlPoint.cpp
If a register has a mapping and is then mapped to a new register, apply the same mapping to the new register. This means, that stack spills moved into one register and then into another will continued to be tracked.
While we are here, remove an old and now irrelevant comment.
> Apply stackmap mappings transitively.

- llvm/include/llvm/CodeGen/Passes.h
- llvm/include/llvm/InitializePasses.h
- llvm/lib/CodeGen/CMakeLists.txt
- llvm/lib/CodeGen/CodeGen.cpp
- llvm/lib/CodeGen/TargetPassConfig.cpp
- llvm/lib/CodeGen/Yk/FixStackmapsSpillReloads.cpp
- llvm/lib/Support/Yk.cpp
- llvm/test/CodeGen/X86/yk-stackmaps-spillreloads-fix.ll
The register allocator may insert spills and spill reloads around function calls. Unfortunately, it doesn't take stackmap instructions into account, so spill reloads may be placed inbetween a call and the stackmap attached to it. This changes the offset of the stackmap and the variables it tracks, which is information we rely upon for deoptimisation.
This adds a new pass which "reverts" these changes, by moving the stackmap instruction back to right below the call, and updates its operand (i.e. tracked variables) as appropriate.
> Fix changes to stackmaps made by the register allocator.

- llvm/include/llvm/Transforms/Yk/Linkage.h
- llvm/lib/CodeGen/TargetPassConfig.cpp
- llvm/lib/Transforms/Yk/CMakeLists.txt
- llvm/lib/Transforms/Yk/Linkage.cpp
- llvm/test/Transforms/Yk/Linkage/YkLinkage.ll
Compiler side fix for https://github.com/ykjit/yk/issues/647.
Depends on https://github.com/ykjit/yk/pull/650 and https://github.com/ykjit/ykllvm/pull/61.
See commit message for a detailed description of what this does.
Associated PRs for yk and yklua coming soon.
(I wanted to test the name mangling aspect of this, but the llvm test suite isn't geared up for multi-object tests. They defer such tests to another repo, which I don't really want to fork and maintain. We can rely on yk and interpreter tests)
> Add the yk-linkage llvm pass.

- llvm/lib/CodeGen/Yk/FixStackmapsSpillReloads.cpp
LLVM's stackmap lowering pass expects a stackmap's operands to end with StackMaps::NextLive, unless the last operand is an implicit register. If we just happened to have updated the last operand with a spill reload we need make sure to add StackMaps::NextLive to the end.
This makes yklua build again.
> Make new stackmaps in the form LLVM expects.

- llvm/include/llvm/Support/Yk.h
- llvm/lib/Support/CommandLine.cpp
- llvm/lib/Support/Yk.cpp
(for compilers that support it)
As `llvm/lib/Support/CMakeLists.txt` explains:
```
...
check_cxx_compiler_flag("-Werror=global-constructors" HAS_WERROR_GLOBAL_CTORS)
if (HAS_WERROR_GLOBAL_CTORS)
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror=global-constructors")
...
```
> Make yk build with `-Werror,-Wglobal-constructors`.

- llvm/include/llvm/CodeGen/StackMaps.h
- llvm/lib/CodeGen/StackMaps.cpp
- llvm/lib/Target/X86/X86AsmPrinter.cpp
- llvm/lib/Transforms/Yk/ControlPoint.cpp
- llvm/test/CodeGen/X86/yk-stackmaps-extrareg.ll
When fixing a bug in our control point pass (which split blocks at the wrong instruction) this shook out another bug in stackmaps. So far we were only able to store one additional location per register. However, there can be cases were we need to store 2 additional locations. We get away with this fix for now but may have to revisit this in the future if even more locations are needed and implement a more general approach.
> Fix multiple locations in stackmaps

- .buildbot.sh
- .buildbot_dockerfile_debian
To avoid crashes with older compilers.
> Use clang 13 in CI.

- llvm/lib/Transforms/Yk/ControlPoint.cpp
Since we can no longer return naturally from the control point there's some things we can remove now that are no longer needed. See commits for details.
> Simplify the control point.

- llvm/lib/Transforms/Yk/ControlPoint.cpp
Without this, it's impossible to run `./configure` scripts, because they repeatedly run the compiler (e.g. ykllvm's clang) with little programs to see what it does.
> Allow programs without a control point to be compiled.

- llvm/lib/Transforms/Yk/ShadowStack.cpp
Struct litereals in LLVM never have names so we mustn't call `getName` on them.
> Fix checking name of struct literals in shadow stack pass.

- clang/test/Yk/yk_stackmapspillreloads_bug.c
- llvm/lib/CodeGen/Yk/FixStackmapsSpillReloads.cpp
This pass replaces stackmap register operands referring to spill reloads with the stack offset of the spill. However, not all stack reloads come from spills. For example, a stack reload could simply try to reload an argument passed via the stack, which breaks this code. We now check the result of `getRestoreSize` which returns "None" if the reload isn't a spill. In such a case we leave the operand as is.
> Fix bug in FixStackmapsSpillReloads pass.

- llvm/lib/YkIR/YkIRWriter.cpp
Amazingly I forgot to raise the compiler-side change for https://github.com/ykjit/yk/pull/850.
The yk tests passed by chance!
[you have no idea how much confusion this caused!]
> Serialise types last.

- llvm/lib/Transforms/Yk/ShadowStack.cpp
Related Issue: https://github.com/ykjit/yk/issues/794 
+ Removing pthread_create error from YKLLVM infavor for future YK pthread_create runtime interception
> Remove pthread_create error from ShadowStack

- llvm/lib/YkIR/YkIRWriter.cpp
Index increments were being missed due to them being passed by value and not reference! This led to the IR using incorrect local variable operands in some cases.
Tests will be added (where possible) to Yk's IR lowering suite.
> Fix instruction index bugs.

- llvm/test/CodeGen/X86/yk-stackmaps-fixspills-implicitbug.ll
This PR follows [PR#86](https://github.com/ykjit/ykllvm/pull/86) and implements a test which triggers thr runtime bug introduced by isImplicit() when compile yklua with unfixed ykllvm's version. We want to make sure that if changes to `FixStackmapsSpillReloads.cpp` triggers this bug again we can catch it with  this `ykllvm` test case.
The test case is generated by first preprocessing whole `yklua` into single `onelua.c` file and then using `cvise`. `cvise` is able to reduce the big c source file (around 25000 loc) to 43 loc `.c` file then is able to trigger the bug with unfixed ykllvm. 
Next, we generated `.ll` file (with ykllvm's  *debug mode* llc) and and just use the stackmap module part  as a test case under `ykllvm/llvm/test/CodeGen/X86`.
> Added test to catch the additional live variable added by implicit.

- clang/lib/CodeGen/BackendUtil.cpp
The call to `PB.parsePassPipeline` will make sure the default pipeline is run. This is now equivalent to how custom pipelines are ran in `LTOBackend`.
> No need to run `buildO0defaultPipeline` manually.

- llvm/lib/YkIR/YkIRWriter.cpp
See commits.
runtime PR ~coming soon~: https://github.com/ykjit/yk/pull/904
> Serialise struct types (and fix unimplemented instructions)

- llvm/include/llvm/Transforms/Yk/NoCallsInEntryBlocks.h
- llvm/lib/CodeGen/StackMaps.cpp
- llvm/lib/CodeGen/TargetPassConfig.cpp
- llvm/lib/Target/X86/X86AsmPrinter.cpp
- llvm/lib/Transforms/Yk/CMakeLists.txt
- llvm/lib/Transforms/Yk/NoCallsInEntryBlocks.cpp
Adds a pass that splits the entry block before the first call instruction, thus ensuring that no calls can exist inside a function's entry block. This makes it easier on the JIT side to detect mappable callbacks from unmappable code (aka external functions) and fixes a soundness issue with our previous StackAdjust solution.
Unfortunately, this change revealed a stackmap bug that was lurking around, so we need to fix them along side this change.
yk companion PR coming up soon.
> Add pass disallowing calls in entry blocks.

- llvm/include/llvm/CodeGen/AsmPrinter.h
- llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
- llvm/test/CodeGen/X86/yk-basic-block-sections.ll
You can call an external symbol (with an address statically unknown) directly.
Required by https://github.com/ykjit/yk/pull/916
> Don't conflate a call with an unknown target with an indirect call.

- llvm/include/llvm/InitializePasses.h
- llvm/include/llvm/Transforms/Yk/SplitBlocksAfterCalls.h
- llvm/lib/CodeGen/CodeGen.cpp
- llvm/lib/CodeGen/TargetPassConfig.cpp
- llvm/lib/Transforms/Yk/CMakeLists.txt
- llvm/lib/Transforms/Yk/SplitBlocksAfterCalls.cpp
- llvm/test/CodeGen/X86/yk-split-blocks-after-calls.ll
This effectively turns call instructions into terminators, making it easier to process traces in yk. A yk PR with major jitmodbuilder changes (rewriting the entire recursion/external call detection logic) is following soon.
> Add pass for splitting blocks after calls.

- llvm/lib/Bitcode/Writer/BitcodeWriter.cpp
- llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
- llvm/lib/CodeGen/TargetLoweringObjectFileImpl.cpp
- llvm/lib/MC/MCObjectFileInfo.cpp
- llvm/lib/Support/Yk.cpp
It's not clear if it's correct to be SHF_ALLOCing these sections, so we err on the side of caution and don't.
For more info, see:
https://github.com/ykjit/yk/issues/923
Companion to https://github.com/ykjit/yk/pull/927
> Don't SHF_ALLOC the blockmap and LLVM bitcode sections.

- llvm/include/llvm/InitializePasses.h
- llvm/include/llvm/Transforms/Yk/BasicBlockTracer.h
- llvm/lib/CodeGen/CodeGen.cpp
- llvm/lib/CodeGen/TargetPassConfig.cpp
- llvm/lib/Transforms/Yk/BasicBlockTracer.cpp
- llvm/lib/Transforms/Yk/CMakeLists.txt
- llvm/test/Transforms/Yk/BasicBlockTracer.ll
Implemented YkBasicBlockTracer module pass.
Functionality:
+ Intercepting LLVM modules BasicBlocks
+ For each BasicBlock the pass calls externally linked YK function `yk_trace_basicblock` with Function and BasicBlock module relative indexes.
+ Guarded by a `yk-basicblock-tracer`
+ Implemented simple test - `llvm/test/Transforms/Yk/BasicBlockTracer.ll` with assertion for IR `yk_trace_basicblock` function call instruction injection.
> Implement BasicBlockTracer pass

- llvm/include/llvm/InitializePasses.h
- llvm/lib/CodeGen/CodeGen.cpp
- llvm/lib/Transforms/Yk/StackMaps.cpp
- llvm/test/CodeGen/X86/yk-insert-stackmaps.ll
Currently stackmaps is inserted before every function unless it's an intrinsic. However, stackmaps is not needed before calls to unmappable functions, as they are not traced and thus never need deopting. This improves `db.lua`'s performance from `89.9ms` (baseline + O2 flag) to `86.3ms`.
> Don't add stackmap after unmappable functions.

- llvm/lib/Transforms/Yk/StackMaps.cpp
- llvm/test/CodeGen/X86/yk-insert-stackmaps.ll
Since external functions aren't traced and thus can't deopt, we recently added a change that omitted generating stackmap calls in these cases. However, we forgot that the control point call as well as yk_promote_* calls required stackmaps. To get things running again, undo this change and come back to it another time.
> Undo recent stackmap change.

- llvm/lib/YkIR/YkIRWriter.cpp
I think this addresses [this comment](https://github.com/ykjit/yk/pull/991#discussion_r1502675230)?
I wasn't sure whether to use `sizeof(uintptr_t)` or `sizeof(void *)`. Are they the same?
(untested btw :) )
> Yk assumes all pointers are the same size as a void pointer.

- llvm/lib/Transforms/Yk/StackMaps.cpp
These changes make sure that stackmap is not inserted after unmappable functions except control point and yk_promote calls. In previous PR https://github.com/ykjit/ykllvm/pull/114 the stackmaps insertion was skipped as control point and yk_promote were treated as external functions, which resulted in some tests failing. This commit make sures that this problem don't occur while retaining the logic of previous PR.
> Resurrecting Stackmap insertion change

- llvm/lib/YkIR/YkIRWriter.cpp
Companion to https://github.com/ykjit/yk/pull/1051
This change adds (to the AOT LLVM module) an array containing the addresses of all global variables in the module.
We can use this to find the addresses of global variables (by index) without leaning on dlsym(3).
> Inject a "global pointers array".

- llvm/lib/YkIR/YkIRWriter.cpp
> Tweak successor lowering / filter out debug instructions from AOT IR.

- llvm/lib/Transforms/Yk/StackMaps.cpp
These changes make sure that stackmap is not inserted after unmappable functions except control point and yk_promote calls.
> Reverting to get back the stackmap changes.

- llvm/lib/Transforms/Yk/StackMaps.cpp
This commit reverts the stackmap change as it breaks the YK test suite.
> Reverting the stackmap change

- llvm/lib/YkIR/YkIRWriter.cpp
A couple of surprising things about C++:
- Two enums may not have a same-named variant (i.e. discriminants are not namespaced by the parent type).
- A class may be named the same as an enum variant, but when you come to use either, you may have to disambiguate with a hint to the compiler.
Further, in quite a few places our names clash with LLVM's.
This change "namespaces" all of our AOT IR enums such that clashes should never happen, and hints are therefore not required.
Note that there is `enum class` from C++11, which is a "scoped enum", but getting at the underlying discriminant number was only implemented in C++23, which I doubt our compiler supports yet. Our stuff requires getting the number.
> Namespace enums in the serialiser.

- llvm/lib/YkIR/YkIRWriter.cpp
We used a loop to get the individual bytes of a constant value and serialise them.
This would crash if we ask for 8-bits from the value, but there are fewer than 8 bits to fetch. E.g. for a i1, you can never fetch a whole byte's worth of bits.
This change ensures we fetch the right number of bits (i.e. fewer than 8 if there are fewer than 8 left).
Test for this in https://github.com/ykjit/yk/pull/1107
> Avoid assertion failure when serialising constant integer values.

- llvm/lib/YkIR/YkIRWriter.cpp
Initially, each LLVM IR instruction had to be lowered to exactly one Yk IR instruction. Why? Because it was easy to implement.
Later we realised we needed to skip certain LLVM instructions (e.g. debug calls).
At this point we added complexity. Due to the way the deserialiser works, we need to emit an instruction count field before emitting the instructions themselves. Therefore we had to first count how many instructions would be emitted in an initial loop, emit this count, then emit the instructions themselves in a second loop.
This change removes the need for the first loop by "patching up" a placeholder instruction count field once the number of instructions is known.
In turn this simplifies the code quite a bit, making it easier to maintain, but also will make it easier for one LLVM …
> Make serialising Yk IR instructions more flexible.

- llvm/lib/YkIR/YkIRWriter.cpp
Until we start optimising traces we don't need to worry about them.
> Ignore `exact` keywords for binary operations.

- llvm/lib/YkIR/YkIRWriter.cpp
There's already one stored in the `YkIRWriter` that we can use.
> Remove superfluous `DataLayout DL(&M)`.

- llvm/lib/Transforms/Yk/StackMaps.cpp
- llvm/lib/YkIR/YkIRWriter.cpp
We currently don't fold stackmaps into the control point during lowering. However, the control point stackmap is required for side-tracing.
We also need to remove the `frameaddr` live variable from the control point's stackmap as this is not required and removing it at runtime is more difficult than doing it here.
> Fold stackmaps into control point during lowering.

- llvm/lib/Transforms/Yk/ShadowStack.cpp
External calls don't use the shadow stack so there's no need to adjust it.
> Don't adjust shadowstack for external calls.

- llvm/lib/Transforms/Yk/ControlPoint.cpp
- llvm/lib/Transforms/Yk/StackMaps.cpp
This allows the control point to find and access its stackmap. We will later use this to get rid of the trace inputs struct.
> Pass the stackmap id into the control point.

- llvm/lib/YkIR/YkIRWriter.cpp
In LLVM IR globals are always pointer-typed, and to access them you always have to use loads and stores.
We are going to carry this assumption to the Yk IRs, so I thought it best to add an assertion.
> Assert type of global variables.

- llvm/lib/YkIR/YkIRWriter.cpp
Required to fix an AOT IR printing crash.
> Add types to unimplemented AOT consts.

- llvm/lib/Transforms/Yk/ControlPoint.cpp
- llvm/lib/Transforms/Yk/StackMaps.cpp
We recently introduced a way to read trace inputs directly via their registers and stack locations in the parent frame. The former trace inputs struct is thus no longer needed. Similarly, we no longer need to use the `frameaddr` intrinsic which can be removed too.
> Remove trace inputs struct passed into the control point.

- llvm/lib/YkIR/YkIRWriter.cpp
Small QOL improvement. See yk PR: https://github.com/ykjit/yk/pull/1371
> Make safepoint id a u64 rather than an Operand.

- llvm/lib/Target/X86/X86AsmPrinter.cpp
This algorithm works out the additional (register/stack) locations of live variables and stores them inside stackmaps.
There's a part of the algorithm that transitively applies mappings from one register to another (e.g. when one mapping is overwritten). However, we were doing this AFTER we had already overwritten the old mappinng, when we should have applied the old mapping instead.
This commit puts things in the correct order.
> Fix spillmap algorithm.

- llvm/include/llvm/CodeGen/StackMaps.h
- llvm/lib/CodeGen/StackMaps.cpp
- llvm/lib/Target/X86/X86AsmPrinter.cpp
- llvm/lib/Target/X86/X86AsmPrinter.h
This is a collection of fixes for the spillmap algorithm that calculates extra locations for live variables.
> Various spillmap fixes.

- llvm/lib/YkIR/YkIRWriter.cpp
See commits.
In general we should be vigilant every time we feel the urge to write expressions like `bit_size / 8`.
> Byte size fixes/simplifications in IR serialiser.

- llvm/include/llvm/CodeGen/StackMaps.h
- llvm/lib/CodeGen/StackMaps.cpp
- llvm/lib/Target/X86/X86AsmPrinter.cpp
- llvm/test/CodeGen/X86/statepoint-stackmap-size.ll
- llvm/test/CodeGen/X86/yk-stackmaps-extrareg.ll
We've previously relied on a hack to track up to two additional locations per live variable. This worked out for us until now that we are seeing variables with more locations than we can deal with. This commit extends stackmaps properly so that we can track arbitrarily many locations for each live variable.
> Allow tracking of arbitrarily many locations.

- llvm/lib/Target/X86/X86AsmPrinter.cpp
Tickled by software tracing, whose extra calls to the recorder caused LLVM to emit a shape of code we've not seen before.
This is the fix for the CI failure in https://github.com/ykjit/yk/pull/1400
> Fix missing register tracking in the spillmap analysis.

- llvm/include/llvm/InitializePasses.h
- llvm/include/llvm/Transforms/Yk/ControlPoint.h
- llvm/include/llvm/Transforms/Yk/ModuleClone.h
- llvm/include/llvm/Transforms/Yk/Stackmaps.h
- llvm/lib/CodeGen/CodeGen.cpp
- llvm/lib/CodeGen/TargetPassConfig.cpp
- llvm/lib/Transforms/Yk/BasicBlockTracer.cpp
- llvm/lib/Transforms/Yk/CMakeLists.txt
- llvm/lib/Transforms/Yk/ControlPoint.cpp
- llvm/lib/Transforms/Yk/ModuleClone.cpp
- llvm/lib/Transforms/Yk/StackMaps.cpp
- llvm/lib/YkIR/YkIRWriter.cpp
- llvm/test/Transforms/Yk/ModuleClone.ll
YkModuleClone LLVM pass, which creates duplicate versions of functions within a module. 
- Functions that do not have their addresses taken are cloned. This results in two versions of the same function within the module: the original and the cloned version. Cloned functions are renamed by appending a `YK_CLONE_PREFIX` to their original names. It is assumed that each function has unique name within the module.
Example of original and cloned functions in a module
```ir
func func_example(%arg0: i32) -> i32 {
bb0:
....
func __yk_clone_func_example(%arg0: i32) -> i32 {
bb0:
...
```
- Functions whose addresses are taken are left unchanged and are not cloned, ensuring their original version remains in the module.
After cloning, the pass uses llvm::Linker::linkModules() to link the cloned module …
> Module clone pass.

- llvm/lib/Transforms/Yk/StackMaps.cpp
Due to the way the trace builder replaces calls to the promoter with guards, we have to handle the live set slightly differently for them.
Hopefully the comment in the code explains.
> Fix the set of live variables for yk_promote* calls.

- llvm/lib/YkIR/YkIRWriter.cpp
This change permits the yk IR serialiser to serialise calls whose arguments use safe `align` attributes.
Following the precedent of loads and stores, a safe alignment is one that is at least the size of the object being aligned. The JIT's code generator doesn't need to do anything special with such alignments.
(We do plan to change our strategy and encode the alignment requirements explicitly into the IR and defer what to do with it to the JIT codegen, but now isn't the time)
This allows us to handle calls like this:
```
call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(48) %3568, ptr noundef nonnull align 8 dereferenceable(48) %3567, i64 48, i1 false
```
This one was found in the wild in the LuaJIT test suite.
> Allow serialisation of call arguments with safe align attributes.

- llvm/lib/YkIR/YkIRWriter.cpp
> Serialise `fneg` instructions.

- llvm/include/llvm/Support/Yk.h
- llvm/lib/CodeGen/TargetPassConfig.cpp
- llvm/lib/Support/Yk.cpp
- llvm/lib/Transforms/Scalar/JumpThreading.cpp
Requires moving the -yk-patch-ctrl-point flag so it's accessible in two places.
> Prevent JumpThreadingPass from messing with control points.

- llvm/include/llvm/Transforms/Yk/ModuleClone.h
- llvm/lib/Transforms/Yk/ControlPoint.cpp
- llvm/lib/Transforms/Yk/ModuleClone.cpp
- llvm/test/Transforms/Yk/ModuleClone.ll
Ensure that calls in original functions are referencing only original functions.
I encountered this issue when I was building `yklua` with latest `yk` `YKB_TRACER=swt`.
The main issue here is with serialization in `YkIRWriter`, where we don't serialize cloned functions but we still might end up with original functions calling cloned functions.
Lua build error:
```shell
Function not found in function index map: __yk_clone_luaO_tostring
LLVM ERROR: Function not found in function index map
```
[source](https://github.com/ykjit/ykllvm/blob/main/llvm/lib/YkIR/YkIRWriter.cpp#L377)
> Make sure that unoptimised functions calls ONLY unoptimised functions.

- llvm/lib/Transforms/Yk/ShadowStack.cpp
A few bits I noticed when auditing the shadow stack logic last week.
Once this (and the other yk PR) is in, I will make another "sync ykllvm" PR on the yk side.
> More shadow bugs/fixes

- llvm/lib/Target/X86/X86AsmPrinter.cpp
- llvm/test/CodeGen/X86/yk-stackmaps-extrareg.ll
In a couple of places we were failing to clear associations between locations where an MIR instruction defined or killed a register. This lead to us deopting dead stale values at runtime.
> Ensure spillmap entries are properly killed where necessary.

- llvm/include/llvm/InitializePasses.h
- llvm/lib/CodeGen/CodeGen.cpp
- llvm/lib/Transforms/Yk/ShadowStack.cpp
- llvm/test/Transforms/Yk/ShadowStack.ll
- llvm/test/Transforms/Yk/ShadowStackRecurseMain.ll
- llvm/test/Transforms/Yk/ShadowStackZeroMain.ll
**There is some nuance to this, so raising as a draft for now. I will comment on an item I want to discuss before we merge**
Before this change we'd have caller's allocate shadow space. Besides being an unconventional strategy, this also means that we allocate shadow space for things which will never require shadow space. We even had to conservatively allocate shadow space before external calls just in case they call-back into functions that do need shadow space.
This change makes each callee requiring a shadow frame allocate it itself.
Read the comment at the top of ShadowStack.cpp for implementation details.
Measuring about a 22% speedup on bigloop.
> Have callees set up their shadow stack frame.

- llvm/lib/Transforms/Yk/ControlPoint.cpp
Variables that die immediately after the control point are not live and thus don't need to be tracked and passed into traces. This reduces the number of live variables at the control point by one in some tests.
> More accurate live variables at the control point.

- llvm/lib/YkIR/YkIRWriter.cpp
Required by https://github.com/ykjit/yk/pull/1540
> Serialise debug strings

- llvm/lib/Target/X86/X86AsmPrinter.cpp
- llvm/test/CodeGen/X86/yk-stackmaps-extralocs-loop-fix.mir
- llvm/test/CodeGen/X86/yk-stackmaps-extrareg.ll
Our pass which adds additional locations to stackmaps doesn't work correctly in the presence of loops. Here's and example:
```
bb0:
mov rax, [rbp-8]
br bb1
bb1:
STACKMAP [rax]
br bb2
bb2:
mov rax, [rbp-16]
br bb1
```
Here, the first time we enter `bb1` the variable that's stored in `rax` has an extra location `rbp-8`. However, when we enter `bb1` again via `bb2`, the extra location has now changed to `rbp-16`.
Previously, we would process each block only once, and thus, for the above example, encode `rbp-8` as an additional location. However, on the second iteration of the loop, this is no longer correct, so writing to `rbp-8` during deoptimisation can lead to bugs.
In this commit we fix the algorithm but taking loops into account and only encode additional locations into stackmaps that …
> Fix additional stackmap locations in loops.

- llvm/include/llvm/Transforms/Yk/ModuleClone.h
- llvm/include/llvm/Transforms/Yk/ShadowStack.h
- llvm/lib/CodeGen/TargetPassConfig.cpp
- llvm/lib/Transforms/Yk/ModuleClone.cpp
- llvm/lib/Transforms/Yk/ShadowStack.cpp
- llvm/lib/Transforms/Yk/StackMaps.cpp
- llvm/lib/YkIR/YkIRWriter.cpp
The ShadowStack pass, which transforms allocas into shadow stack pointers, is currently ignoring all unoptimised functions ([code reference](https://github.com/ykjit/ykllvm/blob/main/llvm/lib/Transforms/Yk/ShadowStack.cpp#L321)). However, we require these functions to utilise shadow stack pointers, as tracing is performed within them.
Furthermore, the unoptimised main function must be adjusted to use the same shadow stack instance as the optimised main function. This adjustment is essential because the unoptimised and optimised main functions need to share variables stored on the stack, facilitating the transitions between the versions.
This pull request ensures that both the optimised and unoptimised main functions use the same shadow stack. There is no need to establish a mapping …
> Use shadowstack in SWT cloned module

- llvm/lib/Target/X86/X86AsmPrinter.cpp
When spilling a register A, not only update the mapping of this register A, but also the mappings of any other register B that aliases with register A.
Fixes https://github.com/ykjit/yk/issues/1594
> Fix a bug in the spillmap where we would miss copies.

- clang/include/clang/Basic/Attr.td
- clang/include/clang/Basic/AttrDocs.td
- clang/lib/CodeGen/CodeGenModule.cpp
- clang/test/Misc/pragma-attribute-supported-attributes-list.test
- llvm/include/llvm/Support/Yk.h
- llvm/include/llvm/Transforms/Yk/Idempotent.h
- llvm/include/llvm/YkIR/YkIRWriter.h
- llvm/lib/CodeGen/TargetPassConfig.cpp
- llvm/lib/Support/Yk.cpp
- llvm/lib/Transforms/Yk/CMakeLists.txt
- llvm/lib/Transforms/Yk/Idempotent.cpp
- llvm/lib/YkIR/YkIRWriter.cpp
This does a few things:
- adds a `yk_idempotent` function attribute to clang and llvm.
- adds an LLVM pass that records the runtime return values of functions with the annotation.
- adds the `IdempotentPromote` bytecode for the calls to the recorder function (so the JIT can easily identify them later).
For now we only support idempotent functions that return a pointer sized integer.
Required by https://github.com/ykjit/yk/pull/1633
> Implement compiler support for the idempotent hint.

- llvm/include/llvm/CodeGen/StackMaps.h
- llvm/lib/CodeGen/StackMaps.cpp
- llvm/lib/Target/X86/X86AsmPrinter.cpp
- llvm/lib/Target/X86/X86MCInstLower.cpp
Extend the stackmap and patchpoint to track spill offsets for patchpoint instructions. This will allow us to get additional location data for control point live variables.
> Add additional location support for patchpoint instructions.

- llvm/lib/CodeGen/StackMaps.cpp
When a register and an indirect location alias, we attach any extra locations to the register so that they are written to during deopt. This is based on the assumption that stackmaps will always prioritise tracking the register. There was no reason for us to assume this is always the case, and in fact we have now found a bug where the indirect location is tracked instead.
This commit fixes this issue, by checking during stackmap generation if a tracked indirect aliases with a register. If that is the case we emit the register (including the extra locations) into the stackmap in place of the indirect.
> Rewrite indirect locations to register locations if they alias.

- llvm/lib/Transforms/Yk/ShadowStack.cpp
The code we used to align slots on the shadowstack had a small bug, which meant we didn't use the correct alignment. This has been fixed now. We also weren't aligning the entire stack according to the ABI, e.g. on x64 this is typically 16 bytes. This has also been fixed.
> Fix shadowstack alignments.

- llvm/include/llvm/Transforms/Yk/ControlPoint.h
- llvm/lib/Transforms/Yk/ControlPoint.cpp
- llvm/lib/Transforms/Yk/SplitBlocksAfterCalls.cpp
Looks like it could make a small difference to performance.
e.g. CD benchmark
```
===> multitime results before
Mean        Std.Dev.    Min         Median      Max
real        39.678      0.494       39.132      39.529      40.893
user        84.845      5.211       78.563      82.731      94.105
sys         109.256     20.494      84.483      103.518     142.538
===> multitime results after
Mean        Std.Dev.    Min         Median      Max
real        38.924      0.329       38.337      39.031      39.443
user        87.130      3.802       78.461      87.670      91.602
sys         122.228     20.204      83.536      122.193     148.327
```
> Disable block splitting for yk_outline functions.

- llvm/lib/CodeGen/SelectionDAG/CMakeLists.txt
- llvm/lib/CodeGen/SelectionDAG/FastISel.cpp
Again, looks like it might make a small difference to performance:
```
===> multitime results before
1: /home/vext01/research/yklua/src/lua harness.lua cd 3 250
Mean        Std.Dev.    Min         Median      Max
real        38.924      0.329       38.337      39.031      39.443
user        87.130      3.802       78.461      87.670      91.602
sys         122.228     20.204      83.536      122.193     148.327
===> multitime results afer
1: /home/vext01/research/yklua/src/lua harness.lua cd 3 250
Mean        Std.Dev.    Min         Median      Max
real        37.889      0.526       37.069      37.905      38.601
user        82.886      3.734       78.679      82.111      89.148
sys         114.031     18.411      92.995      110.225     149.115
```
> Allow fall-throughs in functions we won't trace.

- llvm/lib/Target/X86/CMakeLists.txt
- llvm/lib/Target/X86/X86AsmPrinter.cpp
- llvm/lib/Transforms/Yk/ControlPoint.cpp
- llvm/lib/Transforms/Yk/ShadowStack.cpp
- llvm/test/CodeGen/X86/yk-stackmaps-extrareg.ll
When I first benchmarked this, did so with a yklua compiled with -O3 (not realising I had that unstaged change still hanging around) and got some good speedups, especially for CD:
```
0   BigLoop     yk     1000000000       2556
1   BigLoop     yk     1000000000       2556
0   Bounce      awfy         1500       4243
1   Bounce      awfy         1500       3291
0   CD          awfy          250     217711
1   CD          awfy          250     123340
0   DeltaBlue   awfy        12000       8709
1   DeltaBlue   awfy        12000       6734
0   Havlak      awfy         1500      26339
1   Havlak      awfy         1500      22691
0   Json        awfy          100      67314
1   Json        awfy          100      55020
0   List        awfy         1500       2015
1   List        awfy …
```
> Don't use the shadow stack in yk_outline functions.

- llvm/include/llvm/Transforms/Yk/ControlPoint.h
- llvm/lib/Transforms/Yk/ControlPoint.cpp
Before we were assuming that any patch point is the control point.
Whilst we don't anticipate any other patchpoints, it would be prudent to check that the target is actually the control point function.
> Improve containsControlPoint().

- clang/test/Yk/idempotent_inlined_promotions.c
- clang/test/Yk/outline_inlined_promotions.c
- llvm/lib/LTO/LTOBackend.cpp
- llvm/lib/Transforms/Yk/Idempotent.cpp
- llvm/lib/Transforms/Yk/StackMaps.cpp
- llvm/lib/YkIR/CMakeLists.txt
- llvm/lib/YkIR/YkIRWriter.cpp
- llvm/test/YkIR/yk_idempotent_not_ykoutline.ll
If a function is marked `yk_outline` (and doesn't contain a control point), then we can never trace it, so *in theory* the optimisations that would otherwise break the mapper could actually be used.
There's one small catch though: the trace builder still has to be able to "outline over" `yk_outline` functions, and if the function has IR, the trace builder will try to map the blocks within and make a total mess of it, since the optimisations skewed the mappings.
This change therefore also prevents ykllvm from emitting AOT IR for those functions, effectively making them appear to the trace builder as foreign code, which is then outlined differently, but crucially *without* the need for the mappings to be consistent.
One knock-on requirement is that no `yk_outline` function is permitted to …
> Enable backend optimisations for functions that can't be traced.

- llvm/include/llvm/Transforms/Yk/ShadowStack.h
- llvm/lib/CodeGen/TargetPassConfig.cpp
- llvm/lib/Passes/CMakeLists.txt
- llvm/lib/Passes/PassBuilder.cpp
- llvm/lib/Passes/PassRegistry.def
- llvm/lib/Transforms/Yk/ShadowStack.cpp
Shadow stack passes can now be invoked with the `opt -passes` argument as well as the old legacy pass manager. This is needed for future shadow stack PRs which will use non-legacy passes during setup in tests.
> Add new pass manager support for shadow stack pass

- llvm/lib/Transforms/Yk/ShadowStack.cpp
- llvm/test/Transforms/Yk/ShadowStackDebug.ll
Debugging the shadow stack inside gdb is hard because it moves all the locals around breaking gdb assumptions. This patch makes it a little easier to debug by creating a 'debug local' for each stack frame which points to the frame's corresponding shadow stack offset. The 'shadowstack' pointer is then visible in gdb with 'info locals'.
This relies solely on LLVM's debug intrinsic library, so does not affect code generation when the '-g' flag is not set.
> Make shadow stack debuggable

- llvm/include/llvm/CodeGen/TargetInstrInfo.h
- llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
- llvm/lib/Target/X86/X86InstrInfo.cpp
- llvm/lib/Target/X86/X86InstrInfo.h
- llvm/lib/Transforms/Yk/StackMaps.cpp
First commit is a correctness fix.
Second (requires the first) is an optimisation.
> Encode synthetic conditional branch info in the blockmap and turn off stackmaps in stuff that can't be traced.

- llvm/lib/Transforms/Yk/ShadowStack.cpp
- llvm/test/Transforms/Yk/ShadowStack.ll
- llvm/test/Transforms/Yk/ShadowStackZeroMain.ll
In order to support VMs which use tracing garbage collection, we need to provide a way for them to scan the shadow stack during marking. The simplest way is export the start pointers and size for the shadow-stack heap allocation.
> Record start pointer and size for the shadow-stack buffer

- llvm/lib/CodeGen/Yk/FixStackmapsSpillReloads.cpp
- llvm/test/CodeGen/X86/yk-stackmaps-fixspills-killedflags.mir
- yk_format_new_files.sh
The `FixStackmapsSpillReloads` moves stackmap instructions back to the
call instruction they belong to, after the register allocator has
inserted spill reloads inbetween.
When doing so, we didn't update `kill` flags or removed tracked
registers from the stackmap that were no longer valid. This has been
fixed and we now run the verifier on any changes we made to make sure
they are sane.
> Various fixes related to the FixStackmapsSpillReloads pass.

- llvm/include/llvm/Transforms/Yk/BasicBlockTracer.h
- llvm/include/llvm/Transforms/Yk/ModuleClone.h
- llvm/include/llvm/Transforms/Yk/Stackmaps.h
- llvm/lib/CodeGen/TargetPassConfig.cpp
- llvm/lib/CodeGen/Yk/FixStackmapsSpillReloads.cpp
- llvm/lib/Transforms/Yk/BasicBlockTracer.cpp
- llvm/lib/Transforms/Yk/ModuleClone.cpp
- llvm/lib/Transforms/Yk/ShadowStack.cpp
- llvm/lib/Transforms/Yk/StackMaps.cpp
- llvm/lib/YkIR/YkIRWriter.cpp
- llvm/test/Transforms/Yk/ModuleClone.ll
- Introduce `__yk_trace_basicblock_dummy` (no-op) alongside existing `__yk_trace_basicblock` calls.
- Optimised functions: Use __yk_trace_basicblock_dummy` calls since they're not executed during tracing phase
- Unoptimized + address-taken functions: Use __yk_trace_basicblock` calls since they may execute during tracing
- Serialise both unopt and opt functions in `YkIRWriter.cpp` if `YkModuleClone` flag is set.
> SWT module clone support for control point transition.

- llvm/lib/CodeGen/StackMaps.cpp
I've tracked the LuLPeg failures down to this optimisation.
The optimisation is supposed to remove duplicate deoptimisations so as to avoid doing unnecessary work at runtime in the deopt routine, however, it appears to delete memory optimisations required for soundness.
This manifested in LuLPeg as follows:
- LEN opcode is used to put the length of a table onto the Lua stack.
- FORPREP opcode is supposed to pick up the result of the LEN opcode for the loop's "limit".
But:
- There is a deopt in the middle of the LEN opcode that (due to the bogus optimisation) fails to flush the result back to the Lua stack, leaving a `nil` on the Lua stack.
- FORPREP quite rightly gets upset that `nil` isn't a valid loop limit.
At the ykllvm level the input to the optimisation is (reg -> extras):
- rdx -> …
> Disable unsound deopt optimisation.

- llvm/lib/Transforms/Yk/OutlineUntraceable.cpp
This is an evolving heuristic, and we're probably going to refine this further but for now it seems that we're better off being conservative with "should we consider this function as traceable or not". Just because a function has its address taken does not mean that it will end up in a trace; right now, at least in yklua, doing so makes performance noticeably worse. Note: this is not a correctness issue. It is purely related to performance.
> Don't consider "address taken" functions to automatically be traceable.

- llvm/lib/CodeGen/TargetPassConfig.cpp
- llvm/lib/Transforms/Yk/ShadowStack.cpp
If a function can't be traced, there's no need for it to have a shadow stack, which in theory means that we can avoid the runtime cost of allocating/freeing shadow stack space and reads/write to the shadow stack.
Implementing this is just a matter of making the "outline untraceable" pass earlier.
However, doing so resulted in seg faults due to the shadow stack pointer not being restored properly after a longjmp(). Hence this change also contains a fix that loads/restores the shadow stack pointer before/after a setjmp() or similar.
Performance impact is a bit of a mixed bag. revcomp speeds up about 11%, but towers slows down about 5% (the latter I checked manually, and this slowdown is real).
Because this fixes a soundness issue, I think we can move forward.
```
Datum1: before-sstack-fix …
```
> Don't insert shadow frames for functions that can't be traced.

- clang/test/Yk/yk_stackmapspillreloads_bug.c
- llvm/include/llvm/Support/Yk.h
- llvm/include/llvm/Transforms/Yk/MarkTraceableOptNone.h
- llvm/lib/CodeGen/TargetPassConfig.cpp
- llvm/lib/LTO/LTOBackend.cpp
- llvm/lib/Support/Yk.cpp
- llvm/lib/Transforms/Yk/CMakeLists.txt
- llvm/lib/Transforms/Yk/MarkTraceableOptNone.cpp
Before we added `optnone` to every function before instruction selection and the backend ran.
This change makes it so we only add `optnone` to things that could be traced.
This means that things marked yk_outline and optimised clone functions do not get marked `optnone`, so in theory they should benefit from a handful of optimisations that they didn't before.
Looks like it might speed us up a few percent, but nothing dramatic.
> Run ISel and backend optimisations on optimised clones.

- .buildbot_dockerfile_debian
- clang/lib/CodeGen/CodeGenModule.cpp
- llvm/include/llvm/Support/Yk.h
- llvm/include/llvm/Transforms/Yk/ModuleClone.h
- llvm/lib/CodeGen/CodeGen.cpp
- llvm/lib/CodeGen/TargetPassConfig.cpp
- llvm/lib/Passes/PassBuilderPipelines.cpp
- llvm/lib/Support/Yk.cpp
- llvm/lib/Transforms/IPO/Inliner.cpp
- llvm/lib/Transforms/Yk/ModuleClone.cpp
This pass moves the position of the module cloner pass much earlier in the pipeline: immediately before the link-time inliner pass.
Optimised clones then have any `noinline` attribute removed, thus allowing them to be inlined into other optimised clones if necessary.
(Why are we talking about `noinline`? Currently early in the pipeline we mark functions containing loops noinline and yk_outline so that they don't end up getting traced, but this isn't required for optimised clones which will never be traced).
Note that the new position of the module clone pass means it would only take effect if the -O optimisation level is >= 2.
Gives about an 8% speedup on storage. According the earlier investigation this is a benchmark that still spends quite a lot of time in optimised clones.
The diff is …
> Move module cloner earlier to allow more AOT inlining of optimised clones
